### ISSUE TITLE
feature request: always open at top changes story order

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TopStoryView#1]
I would like (to discuss) a story river where instead of scrolling through the story to get to an already open tiddler, that the story order itself changed and the jump would actually move the tiddler to the top.  That way anything jumped to, whether new or already open would sit at the top of the story.  This sounds counterintuitive but actually takes full advantage of the nonlinearity of hypertext while in contrast jumping around in a stroy river implies that there is some "right" order to a flow of tiddlers, namely the order they are first opened in.  If everything always moves to the top of the river no matter what context it is opened from, and whatever the source of the jump moves down a notch you always have a sort of archaeology of the story you are creating.  Recent things are near the surface, and tiddlers that have not seen focus in a while are further down.  Saq Imtiaz's always open on top used to do this in TW2, which I think @tobibeer or someone updated.  THis river idea provides a consistency as well, in that you are never scrolled somewhere you don't expect -- whatever you are reading is at the top and focused, and whatever you read just before is immediately below.  WHile it may not seem like a big difference, if you use it for a while it gives a sense of bearings that is less disorienting and easier to manage than scrolling around.  The other way to do this is with a tabbed view instead of a river, in which case the "whose on top" issue becomes irrelevant.  But that is a whole nother thing that would be a differnt plugin.   I already raised this over [at the main TiddlyWiki site](https://github.com/Jermolene/TiddlyWiki5/issues/1290#issuecomment-71426800), in a conversation you were in along wth @tobibeer and others.  If you want to try the tabbed version of TW2, I have one called [FiddlyWiki](http://way.net/FiddlyWiki/FiddlyWiki.html) that you can try to get the idea.  It used to be open-on-top before the tabs, but both basically serve the same function.  

ANyway, thanks for all your work on this and TiddlyMap, and if this is a no-go, you can just tell me to learn to code already and do it myself!  I wish I could.

**Comment by felixhayashi** [comment]
Hi @rcrath 

thanks for the heads up on this. @tobibeer originally suggested this as well.

I think this can be done. However, I would add it as an option to the plugin that is not the default.

**So just to summarize:**

Every internal link clicked should show the corresponging tiddler at top of the river -- no matter if it was open or not.

> ANyway, thanks for all your work on this and TiddlyMap, and if this is a no-go, you can just tell me to learn to code already and do it myself! I wish I could. 

Hehe, I'll see what I can do ;)

-Felix

**Comment by felixhayashi** [comment]
@rcrath 

Ok, I got this to work. tomorrow I want to upload the new version that also shall come with a small plugin config interface.

Good night
-Felix

**Comment by felixhayashi** [comment]
Hi @rcrath 

you can now configure the plugin. To enable this feature change "Navigation behaviour" to "insert".

![selection_584](https://cloud.githubusercontent.com/assets/4307137/6992188/3c8f75e8-dabf-11e4-8d04-04bb64c7dc4e.png)

-Felix

**Comment by rcrath** [comment]
thanks!
