### ISSUE TITLE
Add configuration option to open tiddlers below

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TopStoryView#3]
> Thank you very much for this and well done. I'm using it on a personal TW based tool and it is improving the experience a lot: Tiddlers that would not be visible after navigation (because you can see a small portion of them already) are now displayed perfectly.  Would be possible to change where the tiddlers appears? I like how it navigates but I would prefer to have the tiddlers appearing below the current one.
> https://groups.google.com/d/msgid/tiddlywiki/dac9fa9f-862b-43d1-97a2-2c67b7c0a95a%40googlegroups.com

Scrolling is always until the top is reached, but as @danielo515 points out, insertion/opening could be done at bottom. This should be possible via an option.

What I can do is to
- always open tiddlers at the bottom of the river instead at the top.
- I can also add an option to make the plugin behave completely like "classic" and only always scroll to the top of the newly inserted tiddler or the linked tiddler...

**Comment by danielo515** [comment]
Hello @felixhayashi 

What do you mean like "classic" ? To open the tiddler below and/or on top depending on something I can't figure out.

For me it is ok to appear always at the bottom, as soon as they are not "reallocated" if they are already opened. This is how it works right now and It's perfect. Just add the bottom of the story river also.

**Comment by felixhayashi** [comment]
Hi @danielo515 

thanks for responding here!

> What do you mean like "classic" ? To open the tiddler below and/or on top depending on something I can't figure out.

TiddlyWiki's default story view is called "classic" ;)

> For me it is ok to appear always at the bottom, as soon as they are not "reallocated" if they are already opened.

This answers my question. So...
- you do not want to rearrange tiddlers that are already open. I will add an option that prevents such "reallocation" if open.
- you want tiddlers that do not exist in the river to open at the bottom instead of the very top (correct?)

-Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

> thanks for responding here!
> My pleassure
> 
> TiddlyWiki's default story view is called "classic" ;)

I know, but I don't know what do you mean with copying the behavior. It is opened at the bottom and navigated to it. Is this how classic behaves? I don't care at all :smile:

> you do not want to rearrange tiddlers that are already open. I will add an option that prevents such "reallocation" if open.

Yes that's correct. Is not how it behaves right now? Anyway, is not an high prio, I can live without it or use a pre-release without it.

> you want tiddlers that do not exist in the river to open at the bottom instead of the very top (correct?)

Absolutely correct.

**Comment by felixhayashi** [comment]
Hola

> I don't care at all 

Ok understood :+1: 

> Yes that's correct. Is not how it behaves right now?

Ehm, yes I think you are right!

> Absolutely correct.

Thanks for the clarification. Then I'll add this soon!

**Comment by felixhayashi** [comment]
Hi @danielo515 I am working on a pull request for this one so this gets integrated into the core. Please see https://github.com/Jermolene/TiddlyWiki5/issues/1650#issuecomment-92080513 and https://github.com/Jermolene/TiddlyWiki5/issues/1651

**Comment by felixhayashi** [comment]
Hi @danielo515 

https://github.com/Jermolene/TiddlyWiki5/pull/1662 got accepted and from v5.1.9 on we will be able to decide where tiddlers are opened :dancers: 

Therefore I am closing this

-felix

**Comment by danielo515** [comment]
Hello Felix, 

Glad to hear that! And thanks for informing.
