### ISSUE TITLE
Change order in "open tiddlers" list after rearanging.

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TopStoryView#4]
A "bug" spotted by @twMat at ggroups:

> Small bug(?): If you, for instance on the TiddlyMap site, click tab Open. Then click the edit button on any tiddler not on top (i.e scroll down). This sets the Draft on top... but this is not reflected in tab Open. 
> 
> https://groups.google.com/d/msgid/tiddlywiki/0605cb75-738f-4ccb-82fd-f4f52772bc38%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by felixhayashi** [comment]
This bug is caused because I manipulate the dom which is higly "low level". Instead I should rearrange the entries in the `list` field of the `$:/StoryList` tiddler.

**Comment by felixhayashi** [comment]
Problem is rearranging the story list
- The previously inserted tiddler frame is removed and inserted again
- will result in unnecessary animations in "open tiddlers" list
- also it will trigger another refresh that may cause a loop

**Comment by felixhayashi** [comment]
The problem arises because it is not the story view that decides where a tiddler should originally be displayed but the navigation widget.

I already brought that up here: https://github.com/Jermolene/TiddlyWiki5/issues/1290#issuecomment-69083210

**Comment by twMat** [comment]
Good you're on to it.

**Comment by felixhayashi** [comment]
> Good you're on to it.

since 5 hours :D:D 

Wouldn't be so bad if the sun wasn't shining outside (which is a rare event here in germany) and I am sitting here, stuck with my code.

but I am almost done ;)

**Comment by felixhayashi** [comment]
Spend the whole day trying to fix it but the way tw's storyview mechanism is designed at the moment, it is not possible without being extremely (!) hacky. :( 

So I decided to wait until Jeremy adds some options to the navigator widget (https://github.com/Jermolene/TiddlyWiki5/issues/1651)

**Comment by twMat** [comment]
Thanks Felix for not only developing but also _reporting_ on development including about pauses therein.

**Comment by felixhayashi** [comment]
> but also reporting on development including about pauses therein.

sure. communication is a must !

Good night

**Comment by felixhayashi** [comment]
Hi @twMat I am working on a pull request now that shall solve the issue and also integrates some of the stuff that this plugin does into the core. For updates, please also see https://github.com/Jermolene/TiddlyWiki5/issues/1650#issuecomment-92080513 and https://github.com/Jermolene/TiddlyWiki5/issues/1651

Mr Hayashi

**Comment by felixhayashi** [comment]
@twMat 

https://github.com/Jermolene/TiddlyWiki5/issues/1651 got accepted and will be available as option in v5.1.9

Therefore I am closing this one.

**Comment by twMat** [comment]
Ekzellelte! :-)

FYI, I just posted [#1740](https://github.com/Jermolene/TiddlyWiki5/issues/1740)
