### ISSUE TITLE
Navigating to a tiddler focused moves it to the bottom

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TopStoryView#5]
Hello @felixhayashi 

I just noticed a.. funny? behavior in your view. If you navigate from a tiddler to another, then it appears on top of the first one and navigation occurs. If you click the same button (I did not tried with links) to navigate again to that tiddler without moving the scroll at all, then the tiddler that is on top will appear at bottom. Of course you have to use two tiddlers that fits in the screen at the same time.
I don't know if this could be considered a bug.

Regards.

**Comment by felixhayashi** [comment]
Whoaa that sounds crazy, I have to try that and see it myself ;)

> I don't know if this could be considered a bug.

Sounds like it...

**Comment by felixhayashi** [comment]
Hmm I couldn't reproduce it... you mean like this, and using the "open list" buttons?

![selection_592](https://cloud.githubusercontent.com/assets/4307137/7073359/29ff2954-def3-11e4-8bfb-02d0906d0819.png)

**Comment by danielo515** [comment]
Hello @felixhayashi, 

I think it was a bug on the TW version I was using. I was unable to reproduce it in any other TW than mine. There were other weird behaviors like clicking on tiddlers body triggering navigation to that tiddler. Once I changed TW version none of the problems were reproducible again.

**Comment by felixhayashi** [comment]
![borat_great_success](https://cloud.githubusercontent.com/assets/4307137/7102840/be04e61e-e08f-11e4-98ed-1c9162909f95.jpg)

**Comment by felixhayashi** [comment]
Thanks for telling me, danielo :)
