### ISSUE TITLE
Outsourcing the decision where to open a tiddler to the core

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TopStoryView#7]
Once https://github.com/Jermolene/TiddlyWiki5/pull/1662 is merged, the "top story plugin" shall only be responsible for making tiddlers scroll till they their title is visible at the top of the window. It shall not do any rearrangement anymore.

**Comment by danielo515** [comment]
So you are thinking in a new plugin? What kind of rearrangement was planned?

**Comment by felixhayashi** [comment]
Hi @danielo515,

> So you are thinking in a new plugin? 

no not really. I just want to remove the rearrangement that is currently done by the plugin to the core (see demo of Jermolene/TiddlyWiki5#1662). At the moment, the plugin will _open_ links at top by rearranging the dom positions (because tw adds a tiddler below the current tiddler naturally and I then rearrange afterwards). Then it scrolls till the tiddler reaches the top of the window.

IMO the top story view plugin should only focus on scrolling properly (so the title of a tiddler appears at top after navigation) and it is the job of tiddlywiki to let the user decide where a link should open (below/above/top/bottom).
